server:
  port: 8040

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/quartz
    username: root
    password: 123456


  quartz:
    job-store-type: jdbc
    properties:
       org:
            quartz:
                    scheduler:
                      instanceName: clusteredScheduler
                      instanceId: AUTO
                      skipUpdateCheck: true
                    jobStore:
                      class: org.quartz.impl.jdbcjobstore.JobStoreTX
                      driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
                      tablePrefix: QRTZ_
#                      dataSource: myDs
                      isClustered: true
                      clusterCheckinInterval: 10000
                      useProperties: false
                      txIsolationLevelSerializable: false
                    threadPool:
                      class: org.quartz.simpl.SimpleThreadPool
                      threadCount: 10
                      threadPriority: 5
                      threadsInheritContextClassLoaderOfInitializingThread: true
                    dataSource:
                    #没起作用(配置Quartz数据源)
#                       myDs:
#                           driver: com.mysql.jdbc.Driver
#                           URL: jdbc\:mysql\://127.0.0.1\:3306/test_db?useUnicode\=true&characterEncoding\=UTF-8
#                           user: root
#                           password: 123456
#                           maxConnections: 30

    #没起作用(quartz集群启动时，初始化脚本)
    #jdbc:
      #initialize-schema: always




mybatis:
  type-aliases-package: com.fiberhome.pojo
  mapper-locations: classpath:mapper/*Mapper.xml
logging:
  level:
    org.quartz.core.QuartzScheduler: debug












