server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test_db
    username: root
    password: 123456

  quartz:
    job-store-type: jdbc





mybatis:
  type-aliases-package: com.fiberhome.pojo
  mapper-locations: classpath:mapper/*Mapper.xml
logging:
  level:
    org.quartz.core.QuartzScheduler: debug












