server:
  port: 8020

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test_db
    username: root
    password: 123456

#这里不需要
#  quartz:
#    job-store-type: jdbc





mybatis:
  type-aliases-package: com.fiberhome.pojo
  mapper-locations: classpath:mapper/*Mapper.xml

logging:
  level:
    root: INFO
    org.quartz.core.QuartzScheduler: debug
    com.fiberhome: debug












